select 'SELECT * FROM ' || table_name || ';' from user_tables
where lower(table_name) <> 'informatii_tabel';


SELECT * FROM TARA;
SELECT * FROM LOCATIE;
SELECT * FROM SPECIALIZARE;
SELECT * FROM FACULTATE;
SELECT * FROM CAMIN;
SELECT * FROM STUDENT;
SELECT * FROM EXAMINARE;
SELECT * FROM DISCIPLINA;
SELECT * FROM PROGRAMA;
SELECT * FROM SECRETARA;
SELECT * FROM PROFESOR;
SELECT * FROM ANGAJAT;
SELECT * FROM PARTICIPA;
SELECT * FROM STUDIAZA;